# Generated by Django 5.0.6 on 2024-06-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='name1',
        ),
    ]
